excelFilePath: C:\Work\Projects\Hotfix Viewer Spring\Executables\Excel File\ECPLog.xlsm
allowedHosts: avinasht01,0:0:0:0:0:0:0:1,localhost,127.0.0.1

#ACCESS_CONTROL_ALLOW_ORIGIN
header_acao: http://localhost:7777