application-description: REST application for accessing Hotfix data from Database.
application-version: v3
headerPrefix: test

#Set the flag "use_sample_data" to "true" if you want to load sample data from "SampleHotfixData.json" file into Database.
#Otherwise on PROD it should be set to "false".
app:
  use_sample_data: false
  sheet_name: ECPList
  excelFilePath: C:\Personal\My Project\HotfixService\src\main\resources\data\TestData.xlsx
  headerRowNum: 5 #0-based row index of header names in excel sheet.


spring:
  profiles:
    active: dev
  application:
    name: HFLogViewer_REST

---
spring:
  profiles: dev
  data:
    mongodb:
      authentication-database: testdb
      database: testdb
      host: localhost
      password: test123
      port: 27017
      username: test
server:
  port: 7777

---
spring:
  profiles: prod
  data:
    mongodb:
      authentication-database: prod_xyz
      username: xyz_prod
      password: xyz_prod
      database: prod_xyz
      port: 27017
      host: localhost
server:
  port: 4569


---
logging:
  file:
    name: AplicationBackend.log
  pattern:
    file: "%d %p %c{1.} [%t] %m%n"
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"